ALTER TABLE `SQLWR_TEST`.`PERSON` DROP FOREIGN KEY `FK_HOUSEHOLD_PERSON`;

ALTER TABLE `SQLWR_TEST`.`CAR` DROP FOREIGN KEY `FK_OWNER_CAR_PERSON`;

ALTER TABLE `SQLWR_TEST`.`JOURNEY` DROP FOREIGN KEY `FK_DRIVER_JOURNEY`;
ALTER TABLE `SQLWR_TEST`.`JOURNEY` DROP FOREIGN KEY `FK_CAR_JOURNEY`;

ALTER TABLE `SQLWR_TEST`.`JOURNEY_PASSENGER` DROP FOREIGN KEY `FL_JOURNEY_PASSENGER_JOURNEY`;
ALTER TABLE `SQLWR_TEST`.`JOURNEY_PASSENGER` DROP FOREIGN KEY `FL_JOURNEY_PASSENGER_PASSENGER`;

DROP TABLE IF EXISTS `SQLWR_TEST`.`HOUSEHOLD`;
CREATE TABLE `SQLWR_TEST`.`HOUSEHOLD` (
  `HOUSEHOLD_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(1000),
  `DESCRIPTION` VARCHAR(1000),
  PRIMARY KEY(`HOUSEHOLD_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `SQLWR_TEST`.`PERSON`;
CREATE TABLE `SQLWR_TEST`.`PERSON` (
  `PERSON_ID` INT NOT NULL AUTO_INCREMENT,
  `STATUS_ID` TINYINT(1) NOT NULL DEFAULT 1,
  `FIRST_NAME` VARCHAR(100) NOT NULL,
  `LAST_NAME` VARCHAR(100) NOT NULL,
  `MIDDLE_NAME` VARCHAR(100),
  `DATE_OF_BIRTH` DATE,
  `HOUSEHOLD_ID` INT NOT NULL,
  `DATE_CREATED` DATETIME DEFAULT current_timestamp(),
  `DATE_MODIFIED` DATETIME DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`PERSON_ID`),
  CONSTRAINT `FK_HOUSEHOLD_PERSON` FOREIGN KEY (`HOUSEHOLD_ID`) REFERENCES `HOUSEHOLD` (`HOUSEHOLD_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `SQLWR_TEST`.`CAR`;
CREATE TABLE `SQLWR_TEST`.`CAR` (
  `CAR_ID` INT NOT NULL AUTO_INCREMENT,
  `OWNER_ID` INT NOT NULL,
  `MILEAGE` INT(11) default 0,
  `MAKE` VARCHAR(1000),
  `MODEL` VARCHAR(1000),
  PRIMARY KEY(`CAR_ID`),
  CONSTRAINT `FK_OWNER_CAR_PERSON` FOREIGN KEY (`OWNER_ID`) REFERENCES `PERSON` (`PERSON_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `SQLWR_TEST`.`JOURNEY`;
CREATE TABLE `SQLWR_TEST`.`JOURNEY` (
  `JOURNEY_ID` INT NOT NULL AUTO_INCREMENT,
  `CAR_ID` INT NOT NULL,
  `DRIVER_ID` INT NOT NULL,
  `DESCRIPTION` VARCHAR(4000),
  `START_TIME` DATETIME NOT NULL,
  `END_TIME` DATETIME,
  `COMPLETED` TINYINT(1) NOT NULL DEFAULT 0,
  `DISTANCE` FLOAT,
  PRIMARY KEY(`JOURNEY_ID`),
  CONSTRAINT `FK_DRIVER_JOURNEY` FOREIGN KEY (`DRIVER_ID`) REFERENCES `PERSON` (`PERSON_ID`),
  CONSTRAINT `FK_CAR_JOURNEY` FOREIGN KEY (`CAR_ID`) REFERENCES `CAR` (`CAR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

DROP TABLE IF EXISTS `SQLWR_TEST`.`JOURNEY_PASSENGER`;
CREATE TABLE `SQLWR_TEST`.`JOURNEY_PASSENGER` (
  `JOURNEY_ID` INT NOT NULL,
  `PASSENGER_ID` INT NOT NULL,
  PRIMARY KEY(`JOURNEY_ID`, `PASSENGER_ID`),
  CONSTRAINT `FL_JOURNEY_PASSENGER_JOURNEY` FOREIGN KEY (`JOURNEY_ID`) REFERENCES `JOURNEY` (`JOURNEY_ID`),
  CONSTRAINT `FL_JOURNEY_PASSENGER_PASSENGER` FOREIGN KEY (`PASSENGER_ID`) REFERENCES `PERSON` (`PERSON_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
